// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: event_api/event.proto

package event_api

import (
	_ "github.com/Timofey0880/GoProject2/event-service/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_event_api_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_api_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_api_event_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEventRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateEventRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_event_api_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_api_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_event_api_event_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventResponse) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_event_api_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_api_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_event_api_event_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventRequest) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type GetEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_event_api_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_api_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_event_api_event_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetEventResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetEventResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

var File_event_api_event_proto protoreflect.FileDescriptor

const file_event_api_event_proto_rawDesc = "" +
	"\n" +
	"\x15event_api/event.proto\x12\x10event.service.v1\x1a\x18models/event_model.proto\x1a\x1cgoogle/api/annotations.proto\"P\n" +
	"\x12CreateEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\"0\n" +
	"\x13CreateEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\",\n" +
	"\x0fGetEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\"N\n" +
	"\x10GetEventResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user2\xee\x01\n" +
	"\fEventService\x12t\n" +
	"\vCreateEvent\x12$.event.service.v1.CreateEventRequest\x1a%.event.service.v1.CreateEventResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/event/create\x12h\n" +
	"\bGetEvent\x12!.event.service.v1.GetEventRequest\x1a\".event.service.v1.GetEventResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/event/getBGZEgithub.com/Timofey0880/GoProject2/event-service/internal/pb/event_apib\x06proto3"

var (
	file_event_api_event_proto_rawDescOnce sync.Once
	file_event_api_event_proto_rawDescData []byte
)

func file_event_api_event_proto_rawDescGZIP() []byte {
	file_event_api_event_proto_rawDescOnce.Do(func() {
		file_event_api_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_api_event_proto_rawDesc), len(file_event_api_event_proto_rawDesc)))
	})
	return file_event_api_event_proto_rawDescData
}

var file_event_api_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_event_api_event_proto_goTypes = []any{
	(*CreateEventRequest)(nil),  // 0: event.service.v1.CreateEventRequest
	(*CreateEventResponse)(nil), // 1: event.service.v1.CreateEventResponse
	(*GetEventRequest)(nil),     // 2: event.service.v1.GetEventRequest
	(*GetEventResponse)(nil),    // 3: event.service.v1.GetEventResponse
}
var file_event_api_event_proto_depIdxs = []int32{
	0, // 0: event.service.v1.EventService.CreateEvent:input_type -> event.service.v1.CreateEventRequest
	2, // 1: event.service.v1.EventService.GetEvent:input_type -> event.service.v1.GetEventRequest
	1, // 2: event.service.v1.EventService.CreateEvent:output_type -> event.service.v1.CreateEventResponse
	3, // 3: event.service.v1.EventService.GetEvent:output_type -> event.service.v1.GetEventResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_event_api_event_proto_init() }
func file_event_api_event_proto_init() {
	if File_event_api_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_api_event_proto_rawDesc), len(file_event_api_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_api_event_proto_goTypes,
		DependencyIndexes: file_event_api_event_proto_depIdxs,
		MessageInfos:      file_event_api_event_proto_msgTypes,
	}.Build()
	File_event_api_event_proto = out.File
	file_event_api_event_proto_goTypes = nil
	file_event_api_event_proto_depIdxs = nil
}
