// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: models/event_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventModel) Reset() {
	*x = EventModel{}
	mi := &file_models_event_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventModel) ProtoMessage() {}

func (x *EventModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_event_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventModel.ProtoReflect.Descriptor instead.
func (*EventModel) Descriptor() ([]byte, []int) {
	return file_models_event_model_proto_rawDescGZIP(), []int{0}
}

func (x *EventModel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventModel) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *EventModel) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

var File_models_event_model_proto protoreflect.FileDescriptor

const file_models_event_model_proto_rawDesc = "" +
	"\n" +
	"\x18models/event_model.proto\x12\x0fevent.models.v1\"X\n" +
	"\n" +
	"EventModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04userBDZBgithub.com/Timofey0880/GoProject2/event-service/internal/pb/modelsb\x06proto3"

var (
	file_models_event_model_proto_rawDescOnce sync.Once
	file_models_event_model_proto_rawDescData []byte
)

func file_models_event_model_proto_rawDescGZIP() []byte {
	file_models_event_model_proto_rawDescOnce.Do(func() {
		file_models_event_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_event_model_proto_rawDesc), len(file_models_event_model_proto_rawDesc)))
	})
	return file_models_event_model_proto_rawDescData
}

var file_models_event_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_event_model_proto_goTypes = []any{
	(*EventModel)(nil), // 0: event.models.v1.EventModel
}
var file_models_event_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_event_model_proto_init() }
func file_models_event_model_proto_init() {
	if File_models_event_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_event_model_proto_rawDesc), len(file_models_event_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_event_model_proto_goTypes,
		DependencyIndexes: file_models_event_model_proto_depIdxs,
		MessageInfos:      file_models_event_model_proto_msgTypes,
	}.Build()
	File_models_event_model_proto = out.File
	file_models_event_model_proto_goTypes = nil
	file_models_event_model_proto_depIdxs = nil
}
